server:
  port:
    6001
  servlet:
    context-path: /admin


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cskaoyanmall?serverTimezone=GMT&useSSL=false
    username: root
    password: xjtuse
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  resources:
    static-locations: classpath:static/